version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    ports:
      - "8000:8000"
    container_name: flask-chatbot-app
    networks:
      - chatbot-network

networks:
  chatbot-network:
    name: chatbot-network
    driver: bridge

