version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: interactive_bot_Dockerfile  # Backend service
    expose: 
      - "8000"
    ports:
      - "8000:8000"  
    container_name: my_backend_container
    networks:
      - custom_network

  frontend:
    build:
      context: .
      dockerfile: frontend_Dockerfile  # Frontend service
    expose: 
      - "5001"
    ports:
      - "5001:5001" 
    depends_on:
      - backend  # Make sure the backend starts first
    container_name: my_frontend_container
    networks:
      - custom_network
    env_file:
      - .env 

networks:
  custom_network:
    driver: bridge
